name: .NET

on:
  push:
    branches: [ "main", "test"]
  pull_request:
    branches: [ "main", "test" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Coverlet
      run: dotnet add src/DemoCleanArchitecture/DemoCleanArchitecture.Tests/DemoCleanArchitecture.Tests.csproj package coverlet.msbuild --version 3.1.0

    - name: Restore dependencies
      run: dotnet restore src/DemoCleanArchitecture/DemoCleanArchitecture.sln

    - name: Format Code
      run: dotnet format src/DemoCleanArchitecture/DemoCleanArchitecture.sln
      
    - name: Build
      run: dotnet build src/DemoCleanArchitecture/DemoCleanArchitecture.sln --no-restore

    - name: Test with Coverage
      run: dotnet test src/DemoCleanArchitecture/DemoCleanArchitecture.Tests/DemoCleanArchitecture.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/

    - name: Upload Coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

    - name: Code Quality Check
      run: dotnet format src/DemoCleanArchitecture/DemoCleanArchitecture.sln --verify-no-changes

    - name: Notify team on failure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-message: 'Build falhou na branch: ${{ github.ref }}'
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
